Update Repo URL for users in China

diff --git a/install b/install
--- a/install
+++ b/install
@@ -49,11 +49,11 @@ ioniceCron="/etc/cron.d/make_nas_processes_faster"
 ioniceScript="/usr/sbin/omv-ionice"
 keyserver="hkp://keyserver.ubuntu.com:80"
 omvKey="/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc"
-omvRepo="http://packages.openmediavault.org/public"
+omvRepo="https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/public"
 omvSources="/etc/apt/sources.list.d/openmediavault.list"
 rfkill="/usr/sbin/rfkill"
 smbOptions="min receivefile size = 16384\nwrite cache size = 524288\ngetwd cache = yes"
-url="https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/"
+url="https://cdn.jsdelivr.net/gh/OpenMediaVault-Plugin-Developers/packages@master"
 vsCodeList="/etc/apt/sources.list.d/vscode.list"
 wpaConf="/etc/wpa_supplicant/wpa_supplicant.conf"
 
@@ -116,10 +116,10 @@ fi
 
 
 echo "Updating repos before installing..."
-apt-get --allow-releaseinfo-change update
+apt --allow-releaseinfo-change update
 
 echo "Installing lsb_release..."
-apt-get --yes --no-install-recommends --reinstall install lsb-release
+apt --yes --no-install-recommends --reinstall install lsb-release
 
 arch="$(dpkg --print-architecture)"
 
@@ -162,54 +162,58 @@ if [[ ! ${hostname} =~ ${regex} ]]; then
     exit 6
 fi
 
-# Add Debian signing keys to raspbian to prevent apt-get update failures
+# Add Debian signing keys to raspbian to prevent apt update failures
 # when OMV adds security and/or backports repos
 if grep -rq raspberrypi.org /etc/apt/*; then
   rpi=1
-  echo "Adding Debian signing keys..."
-  for key in AA8E81B4331F7F50 112695A0E562B32A 04EE7237B7D453EC 648ACFD622F3D138; do
-    apt-key adv --no-tty --keyserver ${keyserver} --recv-keys "${key}"
-  done
+  # Already added in arm64 Raspberry Pi OS
+  if [[ "${arch}" == "armhf" ]]; then
+    echo "Adding Debian signing keys..."
+    for key in AA8E81B4331F7F50 112695A0E562B32A 04EE7237B7D453EC 648ACFD622F3D138; do
+      apt-key adv --no-tty --keyserver ${keyserver} --recv-keys "${key}"
+    done
+  fi
   echo "Installing monit from raspberrypi repo..."
-  apt-get --yes --no-install-recommends install -t ${codename} monit
+  apt --yes --no-install-recommends install -t ${codename} monit
 
   # remove vscode repo if found since there is no desktop environment
   # empty file will exist to keep raspberrypi-sys-mods package from adding it back
-  truncate -s 0 "${vsCodeList}"
+  echo "### Disabled by raspberrypi-sys-mods ###" > "${vsCodeList}"
 fi
 
 echo "Install prerequisites..."
-apt-get --yes --no-install-recommends install dirmngr gnupg
+apt --yes --no-install-recommends install dirmngr gnupg
 
 # install openmediavault if not installed already
 omvInstall=$(dpkg -l | awk '$2 == "openmediavault" { print $1 }')
 if [[ ! "${omvInstall}" == "ii" ]]; then
   echo "Installing openmediavault required packages..."
-  if ! apt-get --yes --no-install-recommends install postfix; then
+  if ! apt --yes --no-install-recommends install postfix; then
     echo "failed installing postfix"
     exit 2
   fi
 
   echo "Adding openmediavault repo and key..."
   echo "deb ${omvRepo} ${omvCodename} main" > ${omvSources}
-  wget -O "${omvKey}" ${omvRepo}/archive.key
+  # archive.key does not exist in TUNA Repo
+  wget -O "${omvKey}" https://packages.openmediavault.org/public/archive.key
   apt-key add "${omvKey}"
 
   echo "Updating repos..."
-  if ! apt-get update; then
+  if ! apt update; then
     echo "failed to update apt repos."
     exit 2
   fi
 
   echo "Install openmediavault-keyring..."
-  if ! apt-get --yes install openmediavault-keyring; then
+  if ! apt --yes install openmediavault-keyring; then
     echo "failed to install openmediavault-keyring package."
     exit 2
   fi
 
   monitInstall=$(dpkg -l | awk '$2 == "monit" { print $1 }')
   if [[ ! "${monitInstall}" == "ii" ]]; then
-    if ! apt-get --yes --no-install-recommends install monit; then
+    if ! apt --yes --no-install-recommends install monit; then
       echo "failed installing monit"
       exit 2
     fi
@@ -217,7 +221,7 @@ if [[ ! "${omvInstall}" == "ii" ]]; then
 
   echo "Installing openmediavault..."
   aptFlags="--yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends"
-  cmd="apt-get ${aptFlags} install openmediavault"
+  cmd="apt ${aptFlags} install openmediavault"
   if ! ${cmd}; then
     echo "failed to install openmediavault package."
     exit 2
@@ -247,6 +251,10 @@ if [ ${rpi} -eq 1 ]; then
   omv_set_default "OMV_APT_USE_OS_SECURITY" false true
 fi
 
+# change default OMV EXTRAS repository
+omv-env set OMV_EXTRAS_APT_REPOSITORY_URL "https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/openmediavault-plugin-developers"
+omv-salt stage run all
+
 # install omv-extras
 echo "Downloading omv-extras.org plugin for openmediavault ${version}.x ..."
 file="openmediavault-omvextrasorg_latest_all${version}.deb"
@@ -258,13 +266,13 @@ wget ${url}/${file}
 if [ -f "${file}" ]; then
   if ! dpkg --install ${file}; then
     echo "Installing other dependencies ..."
-    apt-get --yes --fix-broken install
+    apt --yes --fix-broken install
     omvextrasInstall=$(dpkg -l | awk '$2 == "openmediavault-omvextrasorg" { print $1 }')
     if [[ ! "${omvextrasInstall}" == "ii" ]]; then
       echo "omv-extras failed to install correctly.  Trying to fix with ${confCmd} ..."
       if ${confCmd} omvextras; then
         echo "Trying to fix apt ..."
-        apt-get --yes --fix-broken install
+        apt --yes --fix-broken install
       else
         echo "${confCmd} failed and openmediavault-omvextrasorg is in a bad state."
         exit 3
@@ -278,7 +286,7 @@ if [ -f "${file}" ]; then
   fi
 
   echo "Updating repos ..."
-  apt-get update
+  apt update
 else
   echo "There was a problem downloading the package."
 fi
@@ -307,18 +315,18 @@ if [ ${skipFlash} -eq 1 ]; then
   echo "Skipping installation of the flashmemory plugin."
 else
   echo "Install folder2ram..."
-  if apt-get --yes --fix-missing --no-install-recommends install folder2ram; then
+  if apt --yes --fix-missing --no-install-recommends install folder2ram; then
     echo "Installed folder2ram."
   else
     echo "Failed to install folder2ram."
   fi
   echo "Install flashmemory plugin..."
-  if apt-get --yes install openmediavault-flashmemory; then
+  if apt --yes install openmediavault-flashmemory; then
     echo "Installed flashmemory plugin."
   else
     echo "Failed to install flashmemory plugin."
     ${confCmd} flashmemory
-    apt-get --yes --fix-broken install
+    apt --yes --fix-broken install
   fi
 fi
 
@@ -475,7 +483,7 @@ if [ ${skipNet} -ne 1 ]; then
   fi
 
   echo "Removing network-manager and dhcpcd5 ..."
-  apt-get -y --autoremove purge network-manager dhcpcd5
+  apt -y --autoremove purge network-manager dhcpcd5
 
   echo "Enable and start systemd-resolved ..."
   systemctl enable systemd-resolved
